apiVersion: v1
entries:
  k10:
  - apiVersion: v2
    appVersion: 1.2.3
    created: "2023-10-06T10:52:52.840042311+05:30"
    dependencies:
    - name: grafana
      repository: file://./dependency_chart/grafana
      version: 6.59.4
    - name: prometheus
      repository: file://./dependency_chart/prometheus
      version: 23.3.0
    description: Kasten’s K10 Data Management Platform
    digest: dacbdbdcdb6d5fad8f6b1dc049036066715de6c48847fe610b012242586d8efc
    home: https://kasten.io/
    icon: https://docs.kasten.io/_static/kasten.png
    maintainers:
    - email: contact@kasten.io
      name: kastenIO
    name: k10
    urls:
    - k10-1.2.3.tgz
    version: 1.2.3
  - apiVersion: v2
    appVersion: v0.1.0-alpha
    created: "2023-10-06T10:52:52.849467173+05:30"
    dependencies:
    - name: grafana
      repository: file://./dependency_chart/grafana
      version: 6.59.4
    - name: prometheus
      repository: file://./dependency_chart/prometheus
      version: 23.3.0
    description: Kasten’s K10 Data Management Platform
    digest: 64dd8aea88f405d44d726c14660401994490f1f34d96f964ec646c4886411e57
    home: https://kasten.io/
    icon: https://docs.kasten.io/_static/kasten.png
    maintainers:
    - email: contact@kasten.io
      name: kastenIO
    name: k10
    urls:
    - k10-v0.1.0-alpha.tgz
    version: v0.1.0-alpha
generated: "2023-10-06T10:52:52.826530377+05:30"
